// 问卷模块定义
export const questionModules = [
    { id: 'values', name: '基础认知与价值观', icon: '🌟' },
    { id: 'relationship', name: '感情观与亲密关系', icon: '❤️' },
    { id: 'marriage', name: '婚姻与家庭', icon: '🏠' },
    { id: 'lifestyle', name: '生活方式与习惯', icon: '🌿' },
    { id: 'social', name: '社交与性格', icon: '👥' },
    { id: 'career', name: '学业与职业', icon: '💼' },
    { id: 'preferences', name: '偏好与底线', icon: '⚖️' },
    { id: 'deep', name: '深度自我与未来', icon: '🔮' },
  ];
  
  // 所有问题
  export const questions = [
    // 一、基础认知与价值观（10题）
    {
      id: 1,
      moduleId: 'values',
      text: '你人生中最重要的5项核心价值观是什么？（可多选）',
      type: 'multiple',
      options: ['忠诚', '家庭', '自由', '成就', '健康', '创造力', '安全感', '冒险', '平等', '尊重'],
      weight: 3, // 权重，越高越重要
    },
    {
      id: 2,
      moduleId: 'values',
      text: '你认为“成功”的核心定义是什么？',
      type: 'single',
      options: ['财富自由', '家庭幸福', '社会地位', '自我实现', '影响力', '内心平静'],
      weight: 2,
    },
    {
      id: 3,
      moduleId: 'values',
      text: '你是否相信人可以真正改变世界？',
      type: 'scale', // 1-5分
      weight: 1,
    },
    {
      id: 4,
      moduleId: 'values',
      text: '你做决策更偏向理性分析还是直觉感受？',
      type: 'scale',
      options: ['完全理性', '偏理性', '平衡', '偏直觉', '完全直觉'],
      weight: 2,
    },
    {
      id: 5,
      moduleId: 'values',
      text: '你是否愿意为了理想放弃稳定生活？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 6,
      moduleId: 'values',
      text: '你对“诚信”的底线是什么？',
      type: 'single',
      options: ['绝不撒谎', '善意谎言可以接受', '原则问题不骗', '视情况而定'],
      weight: 3,
    },
    {
      id: 7,
      moduleId: 'values',
      text: '你如何看待物质财富与幸福感的关系？',
      type: 'single',
      options: ['物质是幸福的基础', '物质有一定帮助', '物质不重要', '幸福与物质无关'],
      weight: 2,
    },
    {
      id: 8,
      moduleId: 'values',
      text: '你更倾向于安稳度日还是不断挑战？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 9,
      moduleId: 'values',
      text: '你认为人生必须实现的一件事是什么？',
      type: 'text', // 文本输入
      weight: 1,
    },
    {
      id: 10,
      moduleId: 'values',
      text: '你能接受价值观完全相反的伴侣吗？',
      type: 'scale',
      weight: 3,
    },
  
    // 二、感情观与亲密关系（12题）
    {
      id: 11,
      moduleId: 'relationship',
      text: '你理想的恋爱频率是每天联系还是保持空间？',
      type: 'scale',
      options: ['每天频繁联系', '每天简单联系', '隔天联系', '每周几次', '随缘联系'],
      weight: 2,
    },
    {
      id: 12,
      moduleId: 'relationship',
      text: '你认为恋爱中最不能触碰的底线是什么？',
      type: 'multiple',
      options: ['欺骗', '出轨', '冷暴力', '控制欲', '不尊重', '不忠诚'],
      weight: 3,
    },
    {
      id: 13,
      moduleId: 'relationship',
      text: '你如何看待吵架与矛盾？必须当天解决吗？',
      type: 'single',
      options: ['必须当天解决', '可以冷静一下', '顺其自然', '不喜欢吵架'],
      weight: 2,
    },
    {
      id: 14,
      moduleId: 'relationship',
      text: '你希望伴侣是灵魂知己还是生活搭档？',
      type: 'scale',
      options: ['灵魂知己', '偏灵魂', '平衡', '偏生活', '生活搭档'],
      weight: 3,
    },
    {
      id: 15,
      moduleId: 'relationship',
      text: '你能接受异地恋吗？最长能接受多久？',
      type: 'single',
      options: ['不能接受', '3个月以内', '半年以内', '一年以内', '可以长期'],
      weight: 2,
    },
    {
      id: 16,
      moduleId: 'relationship',
      text: '你认为感情中忠诚的定义是什么？',
      type: 'multiple',
      options: ['身体忠诚', '精神忠诚', '情感忠诚', '完全独占', '适度空间'],
      weight: 3,
    },
    {
      id: 17,
      moduleId: 'relationship',
      text: '你更在意情绪价值还是现实条件？',
      type: 'scale',
      options: ['情绪价值', '偏情绪', '平衡', '偏现实', '现实条件'],
      weight: 2,
    },
    {
      id: 18,
      moduleId: 'relationship',
      text: '你希望恋爱多久考虑结婚？',
      type: 'single',
      options: ['半年内', '1-2年', '3-5年', '看感觉', '不结婚'],
      weight: 2,
    },
    {
      id: 19,
      moduleId: 'relationship',
      text: '你能接受伴侣有非常好的异性朋友吗？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 20,
      moduleId: 'relationship',
      text: '你认为爱情最重要的三个要素是什么？',
      type: 'multiple',
      options: ['信任', '尊重', '沟通', '激情', '陪伴', '理解', '支持', '共同成长'],
      weight: 3,
    },
    {
      id: 21,
      moduleId: 'relationship',
      text: '你会主动表达爱意与需求吗？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 22,
      moduleId: 'relationship',
      text: '你能接受伴侣与自己成长节奏不同吗？',
      type: 'scale',
      weight: 2,
    },
  
    // 三、婚姻与家庭（10题）
    {
      id: 23,
      moduleId: 'marriage',
      text: '你是否有结婚计划？大概在什么年龄？',
      type: 'single',
      options: ['25岁前', '25-30', '30-35', '35岁后', '不结婚'],
      weight: 3,
    },
    {
      id: 24,
      moduleId: 'marriage',
      text: '你认为婚姻的意义是什么？',
      type: 'multiple',
      options: ['爱情承诺', '法律保障', '家庭责任', '社会认可', '共同成长'],
      weight: 2,
    },
    {
      id: 25,
      moduleId: 'marriage',
      text: '你是否想要孩子？想要几个？',
      type: 'single',
      options: ['不想要', '1个', '2个', '3个以上', '看情况'],
      weight: 3,
    },
    {
      id: 26,
      moduleId: 'marriage',
      text: '孩子对你来说是人生必需项吗？',
      type: 'scale',
      weight: 3,
    },
    {
      id: 27,
      moduleId: 'marriage',
      text: '你如何看待婚前同居？',
      type: 'scale',
      options: ['完全支持', '可以接受', '中立', '不太接受', '完全反对'],
      weight: 2,
    },
    {
      id: 28,
      moduleId: 'marriage',
      text: '你能接受与父母同住吗？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 29,
      moduleId: 'marriage',
      text: '你认为家庭分工应该如何分配？',
      type: 'single',
      options: ['平等分担', '男主外女主内', '女主外男主内', '谁有空谁做', '请人帮忙'],
      weight: 2,
    },
    {
      id: 30,
      moduleId: 'marriage',
      text: '你对伴侣的家庭背景有要求吗？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 31,
      moduleId: 'marriage',
      text: '你如何处理双方家庭的矛盾？',
      type: 'multiple',
      options: ['直接沟通', '伴侣出面', '保持距离', '妥协让步', '坚持原则'],
      weight: 2,
    },
    {
      id: 32,
      moduleId: 'marriage',
      text: '你认为婚姻中最容易破裂的点是什么？',
      type: 'multiple',
      options: ['经济问题', '信任危机', '沟通不畅', '家庭干涉', '成长不同步', '感情淡化'],
      weight: 2,
    },
  
    // 四、生活方式与习惯（10题）
    {
      id: 33,
      moduleId: 'lifestyle',
      text: '你是早睡早起型还是熬夜型？',
      type: 'scale',
      options: ['早睡早起', '偏早起', '平衡', '偏熬夜', '熬夜型'],
      weight: 1,
    },
    {
      id: 34,
      moduleId: 'lifestyle',
      text: '你平时喜欢宅家还是外出社交？',
      type: 'scale',
      options: ['宅家', '偏宅家', '平衡', '偏社交', '外出社交'],
      weight: 2,
    },
    {
      id: 35,
      moduleId: 'lifestyle',
      text: '你有定期运动的习惯吗？',
      type: 'scale',
      weight: 1,
    },
    {
      id: 36,
      moduleId: 'lifestyle',
      text: '你是否抽烟、喝酒？能接受伴侣抽烟喝酒吗？',
      type: 'multiple',
      options: ['抽烟', '喝酒', '接受伴侣抽烟', '接受伴侣喝酒', '不接受'],
      weight: 2,
    },
    {
      id: 37,
      moduleId: 'lifestyle',
      text: '你平时的消费习惯是节俭还是随性？',
      type: 'scale',
      options: ['非常节俭', '偏节俭', '平衡', '偏随性', '随性消费'],
      weight: 2,
    },
    {
      id: 38,
      moduleId: 'lifestyle',
      text: '你喜欢规划生活还是随性而为？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 39,
      moduleId: 'lifestyle',
      text: '你对干净整洁的要求高吗？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 40,
      moduleId: 'lifestyle',
      text: '你喜欢旅行吗？更喜欢 spontaneity 还是计划型旅行？',
      type: 'scale',
      options: ['说走就走', '偏随性', '平衡', '偏计划', '详细计划'],
      weight: 1,
    },
    {
      id: 41,
      moduleId: 'lifestyle',
      text: '你每周大概会花多少时间社交？',
      type: 'single',
      options: ['很少', '5-10小时', '10-20小时', '20小时以上'],
      weight: 1,
    },
    {
      id: 42,
      moduleId: 'lifestyle',
      text: '你能接受生活习惯差异很大的伴侣吗？',
      type: 'scale',
      weight: 2,
    },
  
    // 五、社交与性格（8题）
    {
      id: 43,
      moduleId: 'social',
      text: '你是内向型、外向型还是中间型？',
      type: 'scale',
      options: ['内向', '偏内向', '中间', '偏外向', '外向'],
      weight: 2,
    },
    {
      id: 44,
      moduleId: 'social',
      text: '你在人群中通常是倾听者还是表达者？',
      type: 'scale',
      weight: 1,
    },
    {
      id: 45,
      moduleId: 'social',
      text: '你对社交媒体的依赖程度高吗？',
      type: 'scale',
      weight: 1,
    },
    {
      id: 46,
      moduleId: 'social',
      text: '完全不用社交软件对你是加分还是减分？',
      type: 'scale',
      weight: 1,
    },
    {
      id: 47,
      moduleId: 'social',
      text: '你交朋友更看重三观还是相处舒服？',
      type: 'scale',
      options: ['三观', '偏三观', '平衡', '偏舒服', '相处舒服'],
      weight: 2,
    },
    {
      id: 48,
      moduleId: 'social',
      text: '压力大时你更倾向独处还是找人倾诉？',
      type: 'scale',
      weight: 1,
    },
    {
      id: 49,
      moduleId: 'social',
      text: '你容易焦虑还是心态平稳？',
      type: 'scale',
      weight: 1,
    },
    {
      id: 50,
      moduleId: 'social',
      text: '你是容易信任别人还是慢热谨慎？',
      type: 'scale',
      weight: 1,
    },
  
    // 六、学业与职业（6题）
    {
      id: 51,
      moduleId: 'career',
      text: '你目前的职业/学业状态是什么？',
      type: 'single',
      options: ['学生', '职场新人', '稳定工作', '创业', '自由职业', '待业'],
      weight: 1,
    },
    {
      id: 52,
      moduleId: 'career',
      text: '你对未来职业发展有明确规划吗？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 53,
      moduleId: 'career',
      text: '你能接受伴侣工作很忙经常出差吗？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 54,
      moduleId: 'career',
      text: '你更在意工作稳定还是发展前景？',
      type: 'scale',
      options: ['稳定', '偏稳定', '平衡', '偏发展', '发展前景'],
      weight: 2,
    },
    {
      id: 55,
      moduleId: 'career',
      text: '你愿意为伴侣更换城市发展吗？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 56,
      moduleId: 'career',
      text: '你认为事业与感情应该如何平衡？',
      type: 'scale',
      weight: 2,
    },
  
    // 七、偏好与底线（6题）
    {
      id: 57,
      moduleId: 'preferences',
      text: '你对伴侣的年龄、身高、地域有硬性要求吗？',
      type: 'multiple',
      options: ['年龄要求', '身高要求', '地域要求', '没有硬性要求'],
      weight: 2,
    },
    {
      id: 58,
      moduleId: 'preferences',
      text: '你最不能接受伴侣的哪一种行为？',
      type: 'multiple',
      options: ['撒谎', '冷暴力', '控制欲', '不尊重', '不忠诚', '过度依赖'],
      weight: 3,
    },
    {
      id: 59,
      moduleId: 'preferences',
      text: '你喜欢什么样的约会方式？',
      type: 'multiple',
      options: ['餐厅吃饭', '看电影', '户外活动', '宅家', '旅行', '咖啡厅聊天'],
      weight: 1,
    },
    {
      id: 60,
      moduleId: 'preferences',
      text: '你在意伴侣的情感经历数量吗？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 61,
      moduleId: 'preferences',
      text: '你能接受恋爱中有各自的隐私空间吗？',
      type: 'scale',
      weight: 2,
    },
    {
      id: 62,
      moduleId: 'preferences',
      text: '你认为两个人最重要的契合点是什么？',
      type: 'multiple',
      options: ['三观', '生活习惯', '兴趣爱好', '性格', '未来规划', '家庭背景'],
      weight: 3,
    },
  
    // 八、深度自我与未来（4题）
    {
      id: 63,
      moduleId: 'deep',
      text: '你最欣赏自己的三个特质是什么？',
      type: 'text',
      weight: 1,
    },
    {
      id: 64,
      moduleId: 'deep',
      text: '你希望五年后过什么样的生活？',
      type: 'text',
      weight: 2,
    },
    {
      id: 65,
      moduleId: 'deep',
      text: '你想从一段亲密关系里获得什么？',
      type: 'multiple',
      options: ['安全感', '陪伴', '成长', '理解', '激情', '归属感', '支持'],
      weight: 3,
    },
    {
      id: 66,
      moduleId: 'deep',
      text: '你觉得自己适合什么样的伴侣？',
      type: 'text',
      weight: 2,
    },
  ];
  
  // 获取某模块的问题
  export function getQuestionsByModule(moduleId: string) {
    return questions.filter(q => q.moduleId === moduleId);
  }